services:
  - type: web
    name: restaurant-management-backend
    env: node
    plan: free
    rootDir: server
    buildCommand: echo "No build step needed for Node.js backend"
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        generateValue: true
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRE
        value: 7d
      - key: CORS_ORIGIN
        fromService:
          type: web
          property: host
